modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL = "https://github.com/Hunter19823/KubeJSBorealis/issues"
license = "All Rights Reserved"

[[mods]]
modId="kubejsborealis"
version="${file.jarVersion}"
displayName="KubeJSBorealis"
logoFile="borealis_icon.png"
authors="ILIKEPIEFOO2"
description='''
KubeJS Integration for the mod Borealis.
Adds a form of documentation to KubeJS via local server.
As well as adds Borealis Webpage support to KubeJS.
Allowing for custom webpages to be created via kubeJS script.
'''

[[dependencies.kubejsborealis]]
           modId="forge"
           mandatory = true
           versionRange = "[35,)"
           ordering = "NONE"
           side="BOTH"

[[dependencies.kubejsborealis]]
           modId="borealis"
           mandatory = true
           versionRange = "[1.1.5,)"
           ordering = "AFTER"
           side="BOTH"

[[dependencies.kubejsborealis]]
            modId="kubejs"
            mandatory = false
            versionRange = "[1603,)"
            ordering = "AFTER"
            side="BOTH"
